name: Get artefact version(s) from provided reference
inputs:
  github_ref:
    type: string
    description: The reference from which the artefact version(s) are created
    required: false
    default: ${{github.ref}}
outputs:
  current_semantic:
    value: "v${{ steps.semantic.outputs.previous_version }}"
  next_semantic:
    value: ${{ steps.semantic.outputs.version_tag }}
  branch_semantic:
    value: ${{ steps.branch_semantic.outputs.value }}
  branch:
    value: ${{ steps.branch.outputs.value }}

runs:
  using: composite
  steps:
    - name: Show inputs
      shell: bash
      run: echo "github_ref=${{inputs.github_ref}}"

    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get the semantic version values for the repo
      id: semantic
      uses: paulhatch/semantic-version@v5.4.0

    - name: Set the branch semantic version value
      id: branch_semantic
      if: ${{startsWith(inputs.github_ref,'refs/heads')}}
      shell: bash
      run: |
        REF=${{inputs.github_ref}}
        echo "value=${{steps.semantic.outputs.version_tag}}-${REF#refs/heads/}-latest" >> $GITHUB_OUTPUT

    - name: Set the branch version value
      id: branch
      if: ${{startsWith(inputs.github_ref,'refs/heads')}}
      shell: bash
      run: |
        REF=${{github.ref_name}}
        echo "value=${REF#refs/heads/}-latest" >> $GITHUB_OUTPUT

