name: Get an artefact version by the ref type that triggered to workflow execution
inputs:
  branch_name:
    type: string
    description: The branch name from which the artefact is created
    required: false
    default: ${{github.ref}}
outputs:
  version:
    value: ${{ steps.version.outputs.value }}

runs:
  using: composite
  steps:
    - name: Set the artefact version value
      id: version
      shell: bash
      run: |
        if [ "${{github.ref_type}}" == "tag" ]
        then
          echo "value=${{github.ref_name}}" >> $GITHUB_OUTPUT
        else
          echo "value=${{github.ref_name}}-latest" >> $GITHUB_OUTPUT
        fi
         